version: '3.8'

networks:
  akter-bling-auth:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - akter-bling-auth
