version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules/bcrypt/
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bling_auth
      DB_USERNAME: bling
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - mysql
    command: npm run dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - akter-bling-auth

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: bling_auth
      MYSQL_USER: bling
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - akter-bling-auth
    ports:
      - "3308:3306"

secrets:
  db_password:
    file: secrets/db_password
  db_root_password:
    file: secrets/db_root_password

volumes:
  db:

networks:
  akter-bling-auth:
    driver: bridge
